// <auto-generated />
using GenshinFarmerCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GenshinFarmerCore.Migrations
{
    [DbContext(typeof(GenshinDbContext))]
    [Migration("20221003150449_AddReferences")]
    partial class AddReferences
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GenshinFarmerCore.Models.Database.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GenshinFarmerCore.Models.Database.Material", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("GenshinFarmerCore.Models.Database.Upgrade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("CharacterId")
                        .HasColumnType("varchar(25)");

                    b.Property<long>("MaterialFiveAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialFiveId")
                        .HasColumnType("varchar(50)");

                    b.Property<long>("MaterialFourAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialFourId")
                        .HasColumnType("varchar(50)");

                    b.Property<long>("MaterialOneAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialOneId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<long>("MaterialThreeAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialThreeId")
                        .HasColumnType("varchar(50)");

                    b.Property<long>("MaterialTwoAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialTwoId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UpgradeType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(25);

                    b.Property<string>("WeaponId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("MaterialFiveId");

                    b.HasIndex("MaterialFourId");

                    b.HasIndex("MaterialOneId");

                    b.HasIndex("MaterialThreeId");

                    b.HasIndex("MaterialTwoId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Upgrades");
                });

            modelBuilder.Entity("GenshinFarmerCore.Models.Database.Weapon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("GenshinFarmerCore.Models.Database.Upgrade", b =>
                {
                    b.HasOne("GenshinFarmerCore.Models.Database.Character", "Character")
                        .WithMany("Upgrades")
                        .HasForeignKey("CharacterId");

                    b.HasOne("GenshinFarmerCore.Models.Database.Material", "MaterialFive")
                        .WithMany("UpgradesFive")
                        .HasForeignKey("MaterialFiveId");

                    b.HasOne("GenshinFarmerCore.Models.Database.Material", "MaterialFour")
                        .WithMany("UpgradesFour")
                        .HasForeignKey("MaterialFourId");

                    b.HasOne("GenshinFarmerCore.Models.Database.Material", "MaterialOne")
                        .WithMany("UpgradesOne")
                        .HasForeignKey("MaterialOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenshinFarmerCore.Models.Database.Material", "MaterialThree")
                        .WithMany("UpgradesThree")
                        .HasForeignKey("MaterialThreeId");

                    b.HasOne("GenshinFarmerCore.Models.Database.Material", "MaterialTwo")
                        .WithMany("UpgradesTwo")
                        .HasForeignKey("MaterialTwoId");

                    b.HasOne("GenshinFarmerCore.Models.Database.Weapon", "Weapon")
                        .WithMany("Upgrades")
                        .HasForeignKey("WeaponId");
                });
#pragma warning restore 612, 618
        }
    }
}
